services:
  mongodb:
    image: mongo:latest
    container_name: BW_DB
    ports:
      - "29017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - BW_DB:/data/db

volumes:
  BW_DB:
    driver: local